api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
api_login_check:
    path: /api/login
    methods: [POST]
